// Auto-generated by skills/codebase-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {
  "/architecture/": [
    {
      "text": "架构分析",
      "items": [
        {
          "text": "A-001 Telegraph DI 容器与多平台代码维护范式",
          "link": "/architecture/20260504-di-and-cross-platform-paradigm"
        },
        {
          "text": "A-002 Telegraph 多进程拓扑（main / daemon / shared / pagelet / preload / renderer）",
          "link": "/architecture/20260504-multi-process-topology"
        },
        {
          "text": "A-003 Telegraph 性能与稳定性监控体系",
          "link": "/architecture/20260504-stability-and-performance-monitoring"
        }
      ]
    }
  ],
  "/discussion/": [
    {
      "text": "技术讨论",
      "items": []
    }
  ],
  "/reference/": [
    {
      "text": "参考手册",
      "items": []
    }
  ],
  "/roadmap/": [
    {
      "text": "规划路线",
      "items": []
    }
  ]
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX"
  },
  {
    "text": "架构分析",
    "link": "/architecture/20260504-di-and-cross-platform-paradigm"
  }
];
