// Auto-generated by skills/codebase-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {
  "/architecture/": [
    {
      "text": "架构分析",
      "items": [
        {
          "text": "A-001 Telegraph DI 容器与多平台代码维护范式",
          "link": "/architecture/20260504-di-and-cross-platform-paradigm"
        },
        {
          "text": "A-002 Telegraph 多进程拓扑（main / daemon / shared / pagelet / preload / renderer）",
          "link": "/architecture/20260504-multi-process-topology"
        },
        {
          "text": "A-003 Telegraph 性能与稳定性监控体系",
          "link": "/architecture/20260504-stability-and-performance-monitoring"
        },
        {
          "text": "A-004 Multica 源码实现映射与 Telegraph「类 Multica」能力适配路径",
          "link": "/architecture/20260504-multica-implementation-map-and-telegraph-adaptation"
        },
        {
          "text": "A-005 Telegraph Agent Runtime 与 Extension Host 理论基础",
          "link": "/architecture/20260505-telegraph-agent-runtime-extension-host-theory"
        },
        {
          "text": "A-006 Chat 消息到 LLM 数据流（当前架构）",
          "link": "/architecture/20260505-chat-to-llm-data-flow"
        }
      ]
    }
  ],
  "/discussion/": [
    {
      "text": "技术讨论",
      "items": [
        {
          "text": "D-001 Multica 范式与 Pi / pi-subagents 生态下的 Telegraph 多智能体能力对比",
          "link": "/discussion/20260504-multica-vs-pi-multi-agent-for-telegraph"
        },
        {
          "text": "D-002 IPC 与 Trace 通道分离策略",
          "link": "/discussion/20260505-ipc-trace-channel-separation"
        },
        {
          "text": "D-002 Flue 框架的 PI 集成模式与 Role/Connector 机制分析",
          "link": "/discussion/20260506-flue-pi-integration-analysis"
        },
        {
          "text": "D-003 Spawn CLI 与 Embed Orchestra 两种 Agent 调用模式对比",
          "link": "/discussion/20260506-spawn-cli-vs-embed-orchestra-agent-invocation"
        }
      ]
    }
  ],
  "/issue/": [
    {
      "text": "Issue 记录",
      "items": [
        {
          "text": "I-001 Chat 页面 Tailwind 未生效故障复盘",
          "link": "/issue/20260504-chat-tailwind-not-applied-postmortem"
        },
        {
          "text": "I-002 pi-ai 流式首包后卡住与助手长期 pending（llm_trace await sink 死锁）",
          "link": "/issue/20260505-pi-ai-llm-trace-await-sink-deadlock"
        },
        {
          "text": "I-003 Agent Runtime Abstraction - Phase 1 Implementation Debt & Optimization",
          "link": "/issue/20260505-agent-runtime-abstraction-phase1-debt"
        }
      ]
    }
  ],
  "/reference/": [
    {
      "text": "参考手册",
      "items": []
    }
  ],
  "/roadmap/": [
    {
      "text": "规划路线",
      "items": [
        {
          "text": "P-001 Telegraph 多智能体（类 Multica）分阶段路线图",
          "link": "/roadmap/20260504-multi-agent-telegraph-roadmap"
        },
        {
          "text": "P-002 Telegraph Agent Runtime / Extension Host 实施 Phase-Gate 模板",
          "link": "/roadmap/20260505-agent-runtime-extension-host-phase-gates"
        }
      ]
    }
  ]
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX"
  },
  {
    "text": "架构分析",
    "link": "/architecture/20260504-di-and-cross-platform-paradigm"
  },
  {
    "text": "技术讨论",
    "link": "/discussion/20260504-multica-vs-pi-multi-agent-for-telegraph"
  },
  {
    "text": "Issue 记录",
    "link": "/issue/20260504-chat-tailwind-not-applied-postmortem"
  },
  {
    "text": "开发规划",
    "link": "/roadmap/20260504-multi-agent-telegraph-roadmap"
  }
];
