// Auto-generated by skills/codebase-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.
// NOTE: Entries without YAML frontmatter (A-012..A-015, D-011..D-014, R-002, P-004..P-012, M-001)
//       were added manually because the regenerate script only reads YAML frontmatter.

// @ts-nocheck

export const wikiSidebar = {
  "/architecture/": [
    {
      "text": "架构分析",
      "items": [
        {
          "text": "A-001 Telegraph DI 容器与多平台代码维护范式",
          "link": "/architecture/20260504-di-and-cross-platform-paradigm"
        },
        {
          "text": "A-002 Telegraph 多进程拓扑（main / daemon / shared / pagelet / preload / renderer）",
          "link": "/architecture/20260504-multi-process-topology"
        },
        {
          "text": "A-003 Telegraph 性能与稳定性监控体系",
          "link": "/architecture/20260504-stability-and-performance-monitoring"
        },
        {
          "text": "A-004 Multica 源码实现映射与 Telegraph「类 Multica」能力适配路径",
          "link": "/architecture/20260504-multica-implementation-map-and-telegraph-adaptation"
        },
        {
          "text": "A-005 Telegraph Agent Runtime 与 Extension Host 理论基础",
          "link": "/architecture/20260505-telegraph-agent-runtime-extension-host-theory"
        },
        {
          "text": "A-006 Chat 消息到 LLM 数据流（当前架构）",
          "link": "/architecture/20260505-chat-to-llm-data-flow"
        },
        {
          "text": "A-007 Telegraph 多进程架构全貌",
          "link": "/architecture/20260506-pagelet-process-communication"
        },
        {
          "text": "A-008 Telegraph 最终进程架构（Main · Shared · Daemon · Pagelet）",
          "link": "/architecture/20260509-telegraph-final-process-architecture"
        },
        {
          "text": "A-009 Telegraph 运行时目录分层与文件结构约定",
          "link": "/architecture/20260512-runtime-directory-convention-and-file-structure"
        },
        {
          "text": "A-010 VS Code Contribution 模型对 Telegraph 可扩展架构的启示与落地路径",
          "link": "/architecture/20260513-vscode-contribution-model-for-telegraph"
        },
        {
          "text": "A-011 Telegraph 连接拓扑与通信模式",
          "link": "/architecture/20260515-connection-topology-and-patterns"
        },
        {
          "text": "A-012 Memory, Context, and Self-Healing System Design",
          "link": "/architecture/20260505-memory-context-self-healing-design"
        },
        {
          "text": "A-013 Phase 3: Extension Framework & Multi-Framework Support Design",
          "link": "/architecture/20260505-phase3-extension-framework-design"
        },
        {
          "text": "A-014 Refactor Port Management",
          "link": "/architecture/refactor-port-management"
        },
        {
          "text": "A-015 Refactor Port Management (Next)",
          "link": "/architecture/refactor-port-management-next"
        }
      ]
    }
  ],
  "/discussion/": [
    {
      "text": "技术讨论",
      "items": [
        {
          "text": "D-001 Multica 范式与 Pi / pi-subagents 生态下的 Telegraph 多智能体能力对比",
          "link": "/discussion/20260504-multica-vs-pi-multi-agent-for-telegraph"
        },
        {
          "text": "D-002 IPC 与 Trace 通道分离策略",
          "link": "/discussion/20260505-ipc-trace-channel-separation"
        },
        {
          "text": "D-002 Flue 框架的 PI 集成模式与 Role/Connector 机制分析",
          "link": "/discussion/20260506-flue-pi-integration-analysis"
        },
        {
          "text": "D-003 Spawn CLI 与 Embed Orchestra 两种 Agent 调用模式对比",
          "link": "/discussion/20260506-spawn-cli-vs-embed-orchestra-agent-invocation"
        },
        {
          "text": "D-004 Electron 多 Renderer vs 单 Renderer 面板架构调研与 Telegraph 迁移方案",
          "link": "/discussion/20260506-electron-multi-renderer-vs-single-renderer"
        },
        {
          "text": "D-005 Renderer ↔ Pagelet 通道收敛设计（Forwarding Proxy）",
          "link": "/discussion/20260508-renderer-pagelet-channel-convergence"
        },
        {
          "text": "D-006 x-oasis ConnectionOrchestrator 能力缺口分析（telegraph 视角）",
          "link": "/discussion/20260508-x-oasis-orchestrator-capability-gaps"
        },
        {
          "text": "D-007 x-oasis 能力差距盘点 v2（telegraph apps/ 实际落地视角）",
          "link": "/discussion/20260514-x-oasis-capability-gaps-v2"
        },
        {
          "text": "D-008 apps/ 框架层短板审查（D-007 类别 A 落地后视角）",
          "link": "/discussion/20260515-apps-framework-gap-review-after-supervisor"
        },
        {
          "text": "D-009 Renderer SPA 框架选型（React Router v7 + 自实现 KeepAlive）",
          "link": "/discussion/20260515-renderer-spa-framework-selection"
        },
        {
          "text": "D-010 React Native Mobile 接入 Monorepo 调研（目录结构 + 跨平台共享策略）",
          "link": "/discussion/20260515-react-native-mobile-monorepo-integration"
        },
        {
          "text": "D-011 Chat Agent Runtime 接入迁移文档",
          "link": "/discussion/20260517-chat-agent-runtime-integration"
        },
        {
          "text": "D-012 Telegraph vs Open Design Agent 接入方式对比分析",
          "link": "/discussion/20260517-telegraph-vs-open-design-agent-comparison"
        },
        {
          "text": "D-013 Phase 2 Design: Pi-Embedded Runtime & Tool Execution",
          "link": "/discussion/20260505-phase2-piembedded-design"
        },
        {
          "text": "D-014 Phase 3.3: Multi-Framework Adapter Design",
          "link": "/discussion/20260505-phase3.3-multiframework-design"
        }
      ]
    }
  ],
  "/issue/": [
    {
      "text": "Issue 记录",
      "items": [
        {
          "text": "I-001 Chat 页面 Tailwind 未生效故障复盘",
          "link": "/issue/20260504-chat-tailwind-not-applied-postmortem"
        },
        {
          "text": "I-002 pi-ai 流式首包后卡住与助手长期 pending（llm_trace await sink 死锁）",
          "link": "/issue/20260505-pi-ai-llm-trace-await-sink-deadlock"
        },
        {
          "text": "I-003 Agent Runtime Abstraction - Phase 1 Implementation Debt & Optimization",
          "link": "/issue/20260505-agent-runtime-abstraction-phase1-debt"
        },
        {
          "text": "I-003 Renderer ↔ Design Utility RPC Ping 全链路调试复盘（Phase 4–5）",
          "link": "/issue/20260508-renderer-design-rpc-ping-debug"
        }
      ]
    }
  ],
  "/reference/": [
    {
      "text": "参考手册",
      "items": [
        {
          "text": "R-001 x-oasis 本地 source link 配置手册（telegraph）",
          "link": "/reference/20260508-x-oasis-link-to-source-setup"
        },
        {
          "text": "R-002 Event Mapping: Pi-AI → RuntimeEvent",
          "link": "/reference/20260505-event-mapping"
        }
      ]
    }
  ],
  "/roadmap/": [
    {
      "text": "规划路线",
      "items": [
        {
          "text": "P-001 Telegraph 多智能体（类 Multica）分阶段路线图",
          "link": "/roadmap/20260504-multi-agent-telegraph-roadmap"
        },
        {
          "text": "P-002 Telegraph Agent Runtime / Extension Host 实施 Phase-Gate 模板",
          "link": "/roadmap/20260505-agent-runtime-extension-host-phase-gates"
        },
        {
          "text": "P-003 Port Management → ConnectionOrchestrator 迁移计划（design 先行）",
          "link": "/roadmap/20260508-port-management-orchestrator-migration-plan"
        },
        {
          "text": "P-004 Phase 2B Completion Summary: Embedded Tool Loop Implementation",
          "link": "/roadmap/20260505-phase2b-completion-summary"
        },
        {
          "text": "P-005 Phase 3 Completion Summary (3.0-3.2)",
          "link": "/roadmap/20260505-phase3-completion-summary"
        },
        {
          "text": "P-006 Phase 4-5 Implementation Roadmap: Memory, Context & Self-Healing",
          "link": "/roadmap/20260505-phase4-5-implementation-plan"
        },
        {
          "text": "P-007 Phase 3 Final Completion Summary",
          "link": "/roadmap/20260505-phase3-final-completion-summary"
        },
        {
          "text": "P-008 Phase 1 Completion Summary: Runtime Adapter Pattern",
          "link": "/roadmap/20260505-phase1-completion-summary"
        },
        {
          "text": "P-009 Phase 2 Completion Summary: Pi-Embedded Runtime & Session Management",
          "link": "/roadmap/20260505-phase2-completion-summary"
        },
        {
          "text": "P-010 Design-Only ConnectionOrchestrator Rewrite Plan (Archived)",
          "link": "/roadmap/20260508-design-only-orchestrator-rewrite-plan"
        },
        {
          "text": "P-011 Telegraph (Design) — From-Zero Build Plan",
          "link": "/roadmap/20260508-from-zero-design-only-electron-app-plan"
        },
        {
          "text": "P-012 x-oasis Supervisor & 协议层 — 下一步路线图",
          "link": "/roadmap/20260514-x-oasis-supervisor-next-steps"
        },
        {
          "text": "M-001 Phase 3 Major Milestone: Extensible Agent Runtime Host",
          "link": "/roadmap/20260505-phase3-major-milestone"
        }
      ]
    }
  ]
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX"
  },
  {
    "text": "架构分析",
    "link": "/architecture/20260504-di-and-cross-platform-paradigm"
  },
  {
    "text": "技术讨论",
    "link": "/discussion/20260504-multica-vs-pi-multi-agent-for-telegraph"
  },
  {
    "text": "Issue 记录",
    "link": "/issue/20260504-chat-tailwind-not-applied-postmortem"
  },
  {
    "text": "参考手册",
    "link": "/reference/20260508-x-oasis-link-to-source-setup"
  },
  {
    "text": "开发规划",
    "link": "/roadmap/20260504-multi-agent-telegraph-roadmap"
  }
];
