export const MAIN_WINDOW_DEFAULT_WIDTH = 1280
export const MAIN_WINDOW_DEFAULT_HEIGHT = 800
export const MAIN_WINDOW_DEFAULT_MIN_WIDTH = 960
export const MAIN_WINDOW_DEFAULT_MIN_HEIGHT = 640

export const EXPLORER_WINDOW_DEFAULT_WIDTH = 620
export const EXPLORER_WINDOW_DEFAULT_HEIGHT = 480
export const EXPLORER_WINDOW_DEFAULT_MIN_WIDTH = 620
export const EXPLORER_WINDOW_DEFAULT_MIN_HEIGHT = 480

export enum COMMANDS {
  'CREATE_PANEL' = 'redcity:create-panel',
}
