// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string

declare const MAIN_WINDOW_VITE_NAME: string

declare module '*.css'

// Model configuration types
interface EnvModelConfig {
  provider: string
  modelId: string
  apiKey: string
  baseUrl?: string
  label?: string
  isAvailable: boolean
}

interface ModelEnvConfig {
  models: EnvModelConfig[]
  loadedFromEnv: boolean
}

interface TestModelResult {
  provider: string
  modelId: string
  success: boolean
  error?: string
  latency?: number
}

// Extend the window.telegraph interface
interface TelegraphGlobals {
  ipcRenderer: {
    send(channel: string, ...args: any[]): void
    invoke(channel: string, ...args: any[]): Promise<any>
    on(channel: string, listener: (event: any, ...args: any[]) => void): void
    once(channel: string, listener: (event: any, ...args: any[]) => void): void
    removeListener(channel: string, listener: (event: any, ...args: any[]) => void): void
  }
  webFrame: {
    setZoomLevel(level: number): void
  }
  modelConfig: {
    getConfig(): Promise<ModelEnvConfig>
    getAvailableModels(): Promise<EnvModelConfig[]>
    testModel(config: { provider: string; modelId: string; apiKey: string; baseUrl?: string }): Promise<TestModelResult>
  }
}

declare global {
  interface Window {
    telegraph: TelegraphGlobals
  }
}
