export const MAIN_WINDOW_DEFAULT_WIDTH = 1280
export const MAIN_WINDOW_DEFAULT_HEIGHT = 800
export const MAIN_WINDOW_DEFAULT_MIN_WIDTH = 960
export const MAIN_WINDOW_DEFAULT_MIN_HEIGHT = 640

export const AUXILIARY_WINDOW_DEFAULT_WIDTH = 620
export const AUXILIARY_WINDOW_DEFAULT_HEIGHT = 480
export const AUXILIARY_WINDOW_DEFAULT_MIN_WIDTH = 620
export const AUXILIARY_WINDOW_DEFAULT_MIN_HEIGHT = 480

export const dimensions = {
  primary: {
    width: MAIN_WINDOW_DEFAULT_WIDTH,
    height: MAIN_WINDOW_DEFAULT_HEIGHT,
    minWidth: MAIN_WINDOW_DEFAULT_MIN_WIDTH,
    minHeight: MAIN_WINDOW_DEFAULT_MIN_HEIGHT,
  },
  auxiliary: {
    width: AUXILIARY_WINDOW_DEFAULT_WIDTH,
    height: AUXILIARY_WINDOW_DEFAULT_HEIGHT,
    minWidth: AUXILIARY_WINDOW_DEFAULT_MIN_WIDTH,
    minHeight: AUXILIARY_WINDOW_DEFAULT_MIN_HEIGHT,
  },
}
